name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
env:
  BUILD_TYPE: Release
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build_matrix:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
        cxx: [clang++-12, clang++-13, clang++-14, g++-9, g++-10, g++-11, g++-12]
        exclude:
          - os: ubuntu-20.04
            cxx: clang++-13
          - os: ubuntu-20.04
            cxx: clang++-14
          - os: ubuntu-20.04
            cxx: g++-11
          - os: ubuntu-20.04
            cxx: g++-12
    runs-on: ${{ matrix.os }}
    env:
      CXX: /usr/bin/${{ matrix.cxx }}
    steps:
      - name: Install deps
        run: |
          sudo apt-get install -y \
            libgmock-dev \
            libgrpc++-dev \
            libgtest-dev \
            libprotobuf-dev \
            ninja-build \
            protobuf-compiler \
            protobuf-compiler-grpc
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Configure CMake
        run: |
          cmake -B ${{ github.workspace }}/build \
            -GNinja \
            -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
      - name: Build
        run: |
          cmake --build ${{ github.workspace }}/build \
            --config ${{ env.BUILD_TYPE }}
      - name: Test
        working-directory: ${{ github.workspace }}/build
        run: ctest -C ${{ env.BUILD_TYPE }} --output-junit ctest-junit.xml
      - uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: test-results
          path: ${{ github.workspace }}/build/ctest-junit.xml
